config {
  type: "view"
}
-- Do not use results of this view for aggregation. Results are not one-to-one
select 
account.account_id,
account.lead_id,
account.md_id,
User.name as account_assist_pa,
accountteammember.teammemberrole as account_assist_pa_role
from ${ref("asbestos_funnel_data__accounts")} as account
left join lt_pa_salesforce.AccountTeamMember on account.account_id = AccountTeamMember.accountid
left join lt_pa_salesforce.User on AccountTeamMember.userid = User.id
